#!/usr/bin/env bash
# ══════════════════════════════════════════════════════════════════
# 02-file-index.sh — File index generator sweep
# ══════════════════════════════════════════════════════════════════
# Architecture: bash lists files with metadata, Claude agent writes
# meaningful descriptions. No heuristic description extraction —
# the LLM reads each file and summarizes it.
#
# Contract:
#   --interval            Print interval (3600s) and exit
#   --check               Gather context only, print what agent would see
#   --run                 Gather context + spawn agent
#   --project <path>      Target a specific project root
# ══════════════════════════════════════════════════════════════════
set -euo pipefail

SWEEP_NAME="file-index"
source "$HOME/.claude-ops/lib/sweep-config.sh"
load_sweep_config "$SWEEP_NAME"

CONF="${HOME}/.claude-ops/control-plane.conf"
CONTEXT_FILE="/tmp/harness_sweep_02_context.md"

# ── Load control-plane config (for non-sweep vars) ──────────────
if [ -f "$CONF" ]; then
  source "$CONF"
fi

# ── Shared infrastructure ────────────────────────────────────────
source "${HOME}/.claude-ops/lib/spawn-sweep-agent.sh"

# ── Helpers ──────────────────────────────────────────────────────
now_iso() { date -u +%Y-%m-%dT%H:%M:%SZ; }

file_mod_date() {
  if [[ "$(uname)" == "Darwin" ]]; then
    stat -f "%Sm" -t "%Y-%m-%d" "$1" 2>/dev/null || echo "unknown"
  else
    stat -c "%y" "$1" 2>/dev/null | cut -d' ' -f1 || echo "unknown"
  fi
}

file_size() {
  if [[ "$(uname)" == "Darwin" ]]; then
    stat -f "%z" "$1" 2>/dev/null || echo "0"
  else
    stat -c "%s" "$1" 2>/dev/null || echo "0"
  fi
}

# ── CLI parsing ──────────────────────────────────────────────────
MODE=""
PROJECT_ROOT_ARG=""
HARNESS_NAME=""

while [ $# -gt 0 ]; do
  case "$1" in
    --interval) echo "$SWEEP_INTERVAL"; exit 0 ;;
    --scope)    echo "$SWEEP_SCOPE"; exit 0 ;;
    --check)    MODE="check"; shift ;;
    --run)      MODE="run"; shift ;;
    --project)  PROJECT_ROOT_ARG="$2"; shift 2 ;;
    --harness)  HARNESS_NAME="$2"; shift 2 ;;
    *) echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
done

[ -z "$MODE" ] && { echo "Usage: $0 [--interval|--check|--run] [--harness <name>|--project <path>]" >&2; exit 1; }

source "$HOME/.claude-ops/lib/harness-jq.sh" 2>/dev/null || true
if [ -n "$HARNESS_NAME" ]; then
  PROJECT_ROOT=$(harness_project_root "$HARNESS_NAME" 2>/dev/null)
elif [ -n "$PROJECT_ROOT_ARG" ]; then
  PROJECT_ROOT="$PROJECT_ROOT_ARG"
else
  PROJECT_ROOT="${PROJECT_ROOT:-}"
fi
[ -z "$PROJECT_ROOT" ] && { echo "ERROR: No project root." >&2; exit 1; }

# ── Directories to scan ──────────────────────────────────────────
SCAN_DIRS=("claude_files" ".claude/scripts" "data/config")

# ══════════════════════════════════════════════════════════════════
# PHASE 1: Gather raw context
# ══════════════════════════════════════════════════════════════════

{
cat <<'HEADER'
# File Index Generator — Context for Agent

You are a file index agent spawned by the harness control plane.
Your job is to generate a useful `claude_files/INDEX.md` for this project.

## Your Mission

1. **Read each file** listed below (use the Read tool) to understand its purpose
2. **Write a 1-sentence description** for each — focus on what it IS and when you'd read it
3. **Generate `claude_files/INDEX.md`** with markdown tables grouped by directory
4. `/quit` when done

## Output Format

```markdown
# File Index
> Auto-generated by file index sweep. Last updated: YYYY-MM-DDTHH:MM:SSZ

## claude_files/
| File | Description | Last modified |
|------|-------------|---------------|
| `file.json` | Your description here | 2026-02-23 |
...

## .claude/scripts/
...
```

## Rules

- **Only use Read, Write, Glob, Bash tools.** Only use Bash for `report-issue`.
- **Report issues you encounter** — If you hit permission errors, config problems, or discover bugs, run: `bash ~/.claude-ops/bin/report-issue.sh --title "..." --severity "..." --category "..." --description "..."`
- Read files efficiently — first 20-30 lines is usually enough to understand purpose.
- For JSON files, check fields like "harness", "mission", "description", "status".
- For scripts, read the comment header.
- For markdown, read the first heading + first paragraph.
- Skip binary files, images, and very large files (>10KB) — just note "large file" in description.
- Write the INDEX.md, then /quit. No commit needed for index files.

## Files to Index

HEADER

total_files=0
for rel_dir in "${SCAN_DIRS[@]}"; do
  dir="$PROJECT_ROOT/$rel_dir"
  [ -d "$dir" ] || continue

  echo "### ${rel_dir}/"
  echo ""
  echo "| File | Size | Last modified | Path |"
  echo "|------|------|---------------|------|"

  while IFS= read -r filepath; do
    [ -f "$filepath" ] || continue
    fname=$(basename "$filepath")
    fsize=$(file_size "$filepath")
    fdate=$(file_mod_date "$filepath")
    # Human-readable size
    if [ "$fsize" -gt 1048576 ]; then
      hsize="$(( fsize / 1048576 ))MB"
    elif [ "$fsize" -gt 1024 ]; then
      hsize="$(( fsize / 1024 ))KB"
    else
      hsize="${fsize}B"
    fi
    echo "| \`$fname\` | $hsize | $fdate | $rel_dir/$fname |"
    total_files=$((total_files + 1))
  done < <(find "$dir" -maxdepth 1 -type f 2>/dev/null | sort)
  echo ""
done

echo ""
echo "**Total: $total_files files across ${#SCAN_DIRS[@]} directories**"

} > "$CONTEXT_FILE"

context_lines=$(wc -l < "$CONTEXT_FILE" | tr -d ' ')

# ── Check mode ───────────────────────────────────────────────────
if [ "$MODE" = "check" ]; then
  echo "Context file: $CONTEXT_FILE ($context_lines lines)"
  jq -n -c --arg ts "$(now_iso)" --arg type "sweep" --arg name "$SWEEP_NAME" \
    --arg action "check" --argjson context_lines "$context_lines" \
    '{ts:$ts, type:$type, name:$name, action:$action, context_lines:$context_lines}'
  exit 0
fi

# ══════════════════════════════════════════════════════════════════
# PHASE 2: Spawn Claude agent
# ══════════════════════════════════════════════════════════════════

PANE=$(spawn_sweep_agent "$SWEEP_NAME" "$PROJECT_ROOT" "$CONTEXT_FILE")

if [ -z "$PANE" ]; then
  jq -n -c --arg ts "$(now_iso)" --arg type "sweep" --arg name "$SWEEP_NAME" \
    --arg action "agent_fail" --arg reason "spawn_sweep_agent returned empty" \
    '{ts:$ts, type:$type, name:$name, action:$action, reason:$reason}'
  exit 0
fi

jq -n -c --arg ts "$(now_iso)" --arg type "sweep" --arg name "$SWEEP_NAME" \
  --arg action "agent_spawned" --arg pane "$PANE" \
  '{ts:$ts, type:$type, name:$name, action:$action, pane:$pane}'
