/**
 * Hook generator — creates hook scripts for program-API pipelines.
 *
 * Stop hooks are generated by installGraphStopHook() in compiler.ts
 * (edge-aware, handles gate-all, conditions, cycles).
 *
 * This module handles:
 *   - Pipeline hooks (PipelineHook[] from phases/agents)
 *   - Launch hooks (spawn workers on events)
 *   - Message hooks (send Fleet Mail on events)
 */
import { join } from "node:path";
import type { PipelineHook } from "./types";
import { getHooksIO } from "./hooks-bridge";

const FLEET_DIR_DEFAULT = join(process.env.HOME || "/tmp", ".claude-fleet");

let _phCounter = 0;

/**
 * Install pipeline hooks (phase-level or agent-level) into a worker's hooks dir.
 * Converts PipelineHook[] into DynamicHook format and writes to hooks.json.
 */
export async function installPipelineHooks(
  hooksDir: string,
  hooks: PipelineHook[],
  registeredBy: string,
): Promise<void> {
  const { addHookToFile, writeScriptFile } = await getHooksIO();

  for (const hook of hooks) {
    const id = `ph-${++_phCounter}`;
    const desc = hook.description || `Pipeline ${hook.event} hook`;

    const dynHook: Record<string, unknown> = {
      id,
      event: hook.event,
      description: desc,
      blocking: hook.blocking ?? (hook.event === "Stop"),
      completed: false,
      added_at: new Date().toISOString(),
      registered_by: registeredBy,
      ownership: "creator",
      status: "active",
      lifetime: "persistent",
    };

    if (hook.check) dynHook.check = hook.check;

    if (hook.command) {
      const filename = writeScriptFile(hooksDir, id, desc, hook.command);
      dynHook.script_path = filename;
    }

    if (hook.type === "launch" && hook.workers) {
      const launchScript = generateLaunchHookScript(hook.workers);
      const filename = writeScriptFile(hooksDir, id, desc, launchScript);
      dynHook.script_path = filename;
    }

    if (hook.type === "message" && hook.to) {
      const messageScript = generateMessageHookScript(hook.to, hook.subject || "", hook.body || "");
      const filename = writeScriptFile(hooksDir, id, desc, messageScript);
      dynHook.script_path = filename;
    }

    if (hook.prompt) {
      dynHook.content = hook.prompt;
    }

    if (hook.matcher) {
      dynHook.condition = { tool: hook.matcher };
    }

    addHookToFile(hooksDir, dynHook);
  }
}

/**
 * Generate a shell script for a "launch" hook that creates workers.
 */
function generateLaunchHookScript(workers: import("./types").AgentSpec[] | string): string {
  if (typeof workers === "string") {
    return `#!/usr/bin/env bash
set -euo pipefail
FLEET_DIR="\${CLAUDE_FLEET_DIR:-${FLEET_DIR_DEFAULT}}"
SESSION_DIR="\${SESSION_DIR:-.}"
nohup bun "$FLEET_DIR/engine/program/bridge.ts" "$SESSION_DIR" --node "${workers}" \\
  >> "$SESSION_DIR/bridge-launch.log" 2>&1 &
exit 0
`;
  }

  const creates = (workers as import("./types").AgentSpec[]).map(w =>
    `fleet create "${w.name}" "${w.role}" --model "${w.model || 'sonnet[1m]'}" &`
  ).join("\n");

  return `#!/usr/bin/env bash
set -euo pipefail
${creates}
wait
exit 0
`;
}

/**
 * Generate tool restriction hooks from allowedTools/deniedTools on an AgentSpec.
 * Creates PreToolUse gate hooks that block disallowed tools.
 */
export async function installToolRestrictionHooks(
  hooksDir: string,
  allowedTools?: string[],
  deniedTools?: string[],
): Promise<void> {
  if (!allowedTools?.length && !deniedTools?.length) return;

  const { addHookToFile, writeScriptFile } = await getHooksIO();

  if (deniedTools && deniedTools.length > 0) {
    const id = `ph-${++_phCounter}`;
    const matcher = deniedTools.join("|");
    const script = `#!/usr/bin/env bash
# Block denied tools: ${deniedTools.join(", ")}
echo "Tool $TOOL_NAME is blocked by pipeline configuration" >&2
exit 1
`;
    const filename = writeScriptFile(hooksDir, id, `Block denied tools`, script);
    addHookToFile(hooksDir, {
      id,
      event: "PreToolUse",
      description: `Pipeline: block tools (${deniedTools.join(", ")})`,
      blocking: true,
      completed: false,
      added_at: new Date().toISOString(),
      registered_by: "program-api",
      ownership: "creator",
      status: "active",
      lifetime: "persistent",
      script_path: filename,
      condition: { tool: matcher },
    });
  }

  if (allowedTools && allowedTools.length > 0) {
    const id = `ph-${++_phCounter}`;
    const allowed = allowedTools.join("|");
    const script = `#!/usr/bin/env bash
# Only allow: ${allowedTools.join(", ")}
# TOOL_NAME is set by the hook runner
if echo "$TOOL_NAME" | grep -qE "^(${allowed})$"; then
  exit 0
fi
echo "Tool $TOOL_NAME is not in the allowlist" >&2
exit 1
`;
    const filename = writeScriptFile(hooksDir, id, `Allow only listed tools`, script);
    addHookToFile(hooksDir, {
      id,
      event: "PreToolUse",
      description: `Pipeline: allowlist (${allowedTools.join(", ")})`,
      blocking: true,
      completed: false,
      added_at: new Date().toISOString(),
      registered_by: "program-api",
      ownership: "creator",
      status: "active",
      lifetime: "persistent",
      script_path: filename,
      // No condition.tool — we want this to match ALL tools and filter in script
    });
  }
}

/**
 * Generate a shell script for a "message" hook that sends Fleet Mail.
 */
function generateMessageHookScript(to: string, subject: string, body: string): string {
  return `#!/usr/bin/env bash
set -euo pipefail
if [ -z "\${FLEET_MAIL_URL:-}" ] || [ -z "\${FLEET_MAIL_TOKEN:-}" ]; then
  echo "WARN: Fleet Mail not configured, skipping message to ${to}" >&2
  exit 0
fi
curl -s -X POST "\${FLEET_MAIL_URL}/api/messages" \\
  -H "Authorization: Bearer \${FLEET_MAIL_TOKEN}" \\
  -H "Content-Type: application/json" \\
  -d "$(cat <<'EOFMSG'
{"to":"${to}","subject":"${subject}","body":"${body}"}
EOFMSG
)" > /dev/null 2>&1 || true
exit 0
`;
}
