/**
 * SDK Launcher — generates TypeScript launcher scripts that use
 * @anthropic-ai/claude-agent-sdk's query() function instead of CLI.
 *
 * When runtime:"sdk" is specified, instead of generating a bash wrapper
 * that shells out to `claude`, we generate a .ts script that calls
 * query() programmatically. This gives fleet agents:
 *   - Programmatic hooks (callbacks, not shell scripts)
 *   - Subagent definitions
 *   - Structured output (JSON schema)
 *   - Session management (resume, fork)
 *   - Abort/cancellation
 *   - Direct result streaming
 */

import { writeFileSync, readFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import type { CompiledWorker, ProgramPipelineState } from "./types";
import type { AgentSpecFile } from "../../shared/types";

/**
 * Generate a TypeScript SDK launcher script for a compiled worker.
 * Returns the path to the generated .ts file.
 */
export function generateSdkLauncher(
  worker: CompiledWorker,
  state: ProgramPipelineState,
  specOverrides?: Partial<AgentSpecFile>,
): string {
  const launcherPath = join(state.sessionDir, `sdk-${worker.name}.ts`);
  const resultsDir = join(state.sessionDir, "results", worker.name);
  mkdirSync(resultsDir, { recursive: true });

  // Read the seed content
  const seedContent = readFileSync(worker.seedPath, "utf-8");

  // Build SDK options
  const opts: Record<string, unknown> = {
    model: worker.model,
    permissionMode: "bypassPermissions",
    allowDangerouslySkipPermissions: true,
    effort: "high",
    cwd: state.workDir,
  };

  if (specOverrides?.allowed_tools?.length) {
    opts.allowedTools = specOverrides.allowed_tools;
  }
  if (specOverrides?.disallowed_tools?.length) {
    opts.disallowedTools = specOverrides.disallowed_tools;
  }
  if (specOverrides?.add_dir?.length) {
    opts.additionalDirectories = specOverrides.add_dir;
  }
  if (specOverrides?.max_turns) {
    opts.maxTurns = specOverrides.max_turns;
  }
  if (specOverrides?.max_budget_usd) {
    opts.maxBudgetUsd = specOverrides.max_budget_usd;
  }
  if (specOverrides?.persist_session === false) {
    opts.persistSession = false;
  }
  if (specOverrides?.json_schema) {
    opts.outputFormat = { type: "json_schema", schema: JSON.parse(specOverrides.json_schema) };
  }

  // System prompt
  if (specOverrides?.system_prompt) {
    opts.systemPrompt = specOverrides.system_prompt;
  } else if (specOverrides?.append_system_prompt) {
    opts.systemPrompt = {
      type: "preset",
      preset: "claude_code",
      append: specOverrides.append_system_prompt,
    };
  }

  // MCP servers
  if (specOverrides?.mcp_servers) {
    opts.mcpServers = specOverrides.mcp_servers;
  }

  // Subagents
  if (specOverrides?.agents) {
    opts.agents = specOverrides.agents;
  }

  // Build environment setup
  const envLines: string[] = [];
  if (specOverrides?.env) {
    for (const [k, v] of Object.entries(specOverrides.env)) {
      envLines.push(`process.env.${k} = ${JSON.stringify(v)};`);
    }
  }

  const script = `#!/usr/bin/env bun
/**
 * SDK Launcher for ${worker.name}
 * Generated by fleet pipeline engine
 * Runtime: sdk (Claude Agent SDK)
 */
import { query } from "@anthropic-ai/claude-agent-sdk";
import { writeFileSync, mkdirSync } from "fs";
import { join } from "path";

// Environment
process.env.WORKER_NAME = ${JSON.stringify(worker.name)};
process.env.PROJECT_ROOT = ${JSON.stringify(state.workDir)};
process.env.RESULTS_DIR = ${JSON.stringify(resultsDir)};
${envLines.join("\n")}

const RESULTS_DIR = ${JSON.stringify(resultsDir)};
mkdirSync(RESULTS_DIR, { recursive: true });

const prompt = ${JSON.stringify(seedContent)};
const options = ${JSON.stringify(opts, null, 2)};

async function main() {
  let sessionId: string | undefined;
  let resultText = "";
  let resultJson: unknown = undefined;

  console.log("[sdk] Starting ${worker.name} (model: ${worker.model})");

  try {
    for await (const message of query({ prompt, options })) {
      // Track session ID
      if (message.type === "system" && message.subtype === "init") {
        sessionId = (message as any).session_id;
        console.log("[sdk] Session:", sessionId?.slice(0, 8));
      }

      // Log assistant messages
      if (message.type === "assistant") {
        const content = (message as any).message?.content;
        if (Array.isArray(content)) {
          for (const block of content) {
            if (block.type === "text" && block.text) {
              process.stdout.write(block.text);
            }
          }
        }
      }

      // Capture result
      if ("result" in message) {
        resultText = (message as any).result || "";
      }

      // Capture JSON result
      if (message.type === "result" && (message as any).json) {
        resultJson = (message as any).json;
      }
    }
  } catch (err: any) {
    console.error("[sdk] Error:", err.message);
    writeFileSync(join(RESULTS_DIR, "error.txt"), err.message);
    process.exit(1);
  }

  // Write results
  if (resultText) {
    writeFileSync(join(RESULTS_DIR, "result.txt"), resultText);
  }
  if (resultJson !== undefined) {
    writeFileSync(join(RESULTS_DIR, "result.json"), JSON.stringify(resultJson, null, 2));
  }
  if (sessionId) {
    writeFileSync(join(RESULTS_DIR, "session-id.txt"), sessionId);
  }

  console.log("\\n[sdk] ${worker.name} complete");
}

main().catch((err) => {
  console.error("[sdk] Fatal:", err);
  process.exit(1);
});
`;

  writeFileSync(launcherPath, script, { mode: 0o755 });
  return launcherPath;
}

/**
 * Generate an SDK launcher script for a standalone fleet run --spec agent.
 * Returns the path to the generated .ts file.
 */
export function generateStandaloneSdkLauncher(
  spec: AgentSpecFile,
  sessionDir: string,
  workDir: string,
): string {
  const name = spec.name;
  const launcherPath = join(sessionDir, `sdk-${name}.ts`);
  const resultsDir = join(sessionDir, "results", name);
  mkdirSync(resultsDir, { recursive: true });

  const prompt = spec.prompt || `You are ${name}. ${spec.role || "Complete your task."}`;
  const model = spec.model || "opus[1m]";

  const opts: Record<string, unknown> = {
    model,
    permissionMode: spec.permission_mode || "bypassPermissions",
    allowDangerouslySkipPermissions: (spec.permission_mode || "bypassPermissions") === "bypassPermissions",
    effort: spec.effort || "high",
    cwd: workDir,
  };

  if (spec.allowed_tools?.length) opts.allowedTools = spec.allowed_tools;
  if (spec.disallowed_tools?.length) opts.disallowedTools = spec.disallowed_tools;
  if (spec.add_dir?.length) opts.additionalDirectories = spec.add_dir;
  if (spec.max_turns) opts.maxTurns = spec.max_turns;
  if (spec.max_budget_usd) opts.maxBudgetUsd = spec.max_budget_usd;
  if (spec.persist_session === false) opts.persistSession = false;
  if (spec.system_prompt) opts.systemPrompt = spec.system_prompt;
  else if (spec.append_system_prompt) {
    opts.systemPrompt = { type: "preset", preset: "claude_code", append: spec.append_system_prompt };
  }
  if (spec.mcp_servers) opts.mcpServers = spec.mcp_servers;
  if (spec.agents) opts.agents = spec.agents;
  if (spec.json_schema) {
    try { opts.outputFormat = { type: "json_schema", schema: JSON.parse(spec.json_schema) }; } catch {}
  }

  const envLines: string[] = [];
  if (spec.env) {
    for (const [k, v] of Object.entries(spec.env)) {
      envLines.push(`process.env.${k} = ${JSON.stringify(v)};`);
    }
  }

  const script = `#!/usr/bin/env bun
/**
 * SDK Launcher for ${name}
 * Generated by fleet run --spec (runtime: sdk)
 */
import { query } from "@anthropic-ai/claude-agent-sdk";
import { writeFileSync, mkdirSync } from "fs";
import { join } from "path";

process.env.WORKER_NAME = ${JSON.stringify(name)};
process.env.PROJECT_ROOT = ${JSON.stringify(workDir)};
process.env.RESULTS_DIR = ${JSON.stringify(resultsDir)};
${envLines.join("\n")}

const RESULTS_DIR = ${JSON.stringify(resultsDir)};
mkdirSync(RESULTS_DIR, { recursive: true });

async function main() {
  let sessionId: string | undefined;
  let resultText = "";

  console.log("[sdk] Starting ${name} (model: ${model})");

  for await (const message of query({
    prompt: ${JSON.stringify(prompt)},
    options: ${JSON.stringify(opts, null, 2)},
  })) {
    if (message.type === "system" && message.subtype === "init") {
      sessionId = (message as any).session_id;
      console.log("[sdk] Session:", sessionId?.slice(0, 8));
    }
    if (message.type === "assistant") {
      const content = (message as any).message?.content;
      if (Array.isArray(content)) {
        for (const block of content) {
          if (block.type === "text" && block.text) process.stdout.write(block.text);
        }
      }
    }
    if ("result" in message) resultText = (message as any).result || "";
  }

  if (resultText) writeFileSync(join(RESULTS_DIR, "result.txt"), resultText);
  if (sessionId) writeFileSync(join(RESULTS_DIR, "session-id.txt"), sessionId);
  console.log("\\n[sdk] ${name} complete");
}

main().catch((err) => { console.error("[sdk] Fatal:", err); process.exit(1); });
`;

  writeFileSync(launcherPath, script, { mode: 0o755 });
  return launcherPath;
}
