/**
 * Configuration resolution: CLI flag > config.json > defaults.json > hardcoded.
 */
import { writeFileSync } from "node:fs";
import { defaultsPath, configPath, exists, workerDir, fleetJsonPath } from "./paths";

// Re-export canonical types from shared module
export type { WorkerConfig, WorkerState, FleetConfig, SystemHook } from "../../shared/types";
export { SYSTEM_HOOKS, HARDCODED_DEFAULTS } from "../../shared/types";
import type { WorkerConfig, WorkerState, FleetConfig } from "../../shared/types";
import { HARDCODED_DEFAULTS } from "../../shared/types";

// Re-export IO utilities (locked writes for shared files, plain writes for local)
export { readJson, writeJson, writeJsonLocked, updateJsonLocked } from "../../shared/io";
import { readJson, writeJson, writeJsonLocked } from "../../shared/io";

/** Get global defaults (file > hardcoded) */
export function getDefaults(): Record<string, unknown> {
  const dp = defaultsPath();
  const fromFile = exists(dp) ? readJson<Record<string, unknown>>(dp) : null;
  return { ...HARDCODED_DEFAULTS, ...fromFile };
}

/** Get worker config */
export function getConfig(project: string, name: string): WorkerConfig | null {
  const cp = configPath(project, name);
  return readJson<WorkerConfig>(cp);
}

/** Get worker state */
export function getState(project: string, name: string): WorkerState | null {
  const sp = `${workerDir(project, name)}/state.json`;
  return readJson<WorkerState>(sp);
}

/** Get fleet.json */
export function getFleetConfig(project: string): FleetConfig | null {
  return readJson<FleetConfig>(fleetJsonPath(project));
}

/** Resolve a config value: config > defaults > hardcoded */
export function resolveValue(project: string, name: string, key: string): unknown {
  const config = getConfig(project, name);
  const defaults = getDefaults();

  // Map effort → reasoning_effort
  const configKey = key === "effort" ? "reasoning_effort" : key;

  if (config) {
    const val = (config as Record<string, unknown>)[configKey];
    if (val !== undefined && val !== null) return val;
  }

  return defaults[key] ?? null;
}

/** Update a config key, write back (locked), regenerate launch.sh */
export function setConfigValue(project: string, name: string, key: string, value: unknown): void {
  const cp = configPath(project, name);
  const config = readJson<Record<string, unknown>>(cp);
  if (!config) throw new Error(`Config not found: ${cp}`);

  const configKey = key === "effort" ? "reasoning_effort" : key;
  config[configKey] = value;
  writeJsonLocked(cp, config);
  generateLaunchSh(project, name);
}

/** Generate launch.sh from config */
export function generateLaunchSh(project: string, name: string): void {
  const config = getConfig(project, name);
  if (!config) throw new Error(`Config not found for ${name}`);

  const dir = workerDir(project, name);
  const runtime = config.runtime || "claude";

  let script: string;

  if (runtime === "codex") {
    const sandboxFlag =
      config.permission_mode === "bypassPermissions"
        ? "--dangerously-bypass-approvals-and-sandbox"
        : "-s danger-full-access -a on-request";

    script = `#!/bin/bash
# Auto-generated by fleet — restart command for ${name} (codex runtime)
# Regenerated on config changes. Do not edit manually.
cd "${config.worktree}"
WORKER_NAME="${name}" \\
WORKER_RUNTIME=codex \\
exec codex \\
  -m "${config.model}" \\
  ${sandboxFlag} \\
  -c model_reasoning_effort=${config.reasoning_effort} \\
  --no-alt-screen \\
  --add-dir "${dir}"
`;
  } else {
    const permFlag =
      config.permission_mode === "bypassPermissions"
        ? "--dangerously-skip-permissions"
        : `--permission-mode "${config.permission_mode}"`;

    script = `#!/bin/bash
# Auto-generated by fleet — restart command for ${name}
# Regenerated on config changes. Do not edit manually.
cd "${config.worktree}"
CLAUDE_CODE_SKIP_PROJECT_LOCK=1 \\
WORKER_NAME="${name}" \\
exec claude \\
  --model "${config.model}" \\
  --effort "${config.reasoning_effort}" \\
  ${permFlag} \\
  --add-dir "${dir}"
`;
  }

  const launchPath = `${dir}/launch.sh`;
  writeFileSync(launchPath, script);
  Bun.spawnSync(["chmod", "+x", launchPath]);
}

/** Parse a CLI string value into a typed value */
export function parseCliValue(raw: string): unknown {
  if (raw === "null") return null;
  if (raw === "true") return true;
  if (raw === "false") return false;
  if (!isNaN(Number(raw)) && raw.trim() !== "") return Number(raw);
  return raw;
}

/** The 12 immutable system hooks (delegated to shared/types.ts) */
import { SYSTEM_HOOKS as _HOOKS } from "../../shared/types";
export function getSystemHooks() { return [..._HOOKS]; }
